### ISSUE TITLE
Support org citation link

### ISSUE THREAD

**Issue by llcc** [amake/orgro#104]
Starting from version 9.5, org-mode has supported citations. AFAIK, orgro hasn’t implemented this feature yet. It would be great if basic link highlighting could be supported.

Reference: https://orgmode.org/manual/Citations.html

**Comment by amake** [comment]
The breadth of Org Mode features never ceases to amaze me.

> It would be great if basic link highlighting could be supported at first.

I am planning to do this.

I note that real Org Cite colors unknown keys with the error face; that's a big complication so I won't support that.

> The next proposal could be for orgro to parse the `.bib` file defined in `#+bibliography:` and display the information in a popup when clicked.

There happens to be a BibTeX parser available for Dart: https://github.com/petitparser/dart-petitparser-examples/tree/main/lib/src/bibtex

**Comment by amake** [comment]
Syntax highlighting and parsing of bibliographies is implemented in v1.41.1, available for testing soon:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)

**Comment by amake** [comment]
I should add that the BibTeX is fairly under-specified, so if you find that a bibliography doesn't parse or has fields that need special handling, please report.

**Comment by llcc** [comment]
Link highlighting works great, now my org-mode document looks much better.

I tried to tap the citation link in orgro changelog, which shows a popup, but it says "No bibliographies found". 
My bibliographies are defined as `#+bibliography: Reference.bib` and the file is within the same directory.

**Comment by amake** [comment]
Can you please supply your .org file, or a minimal snippet that includes the `#+bibliography:` line?

**Comment by llcc** [comment]
Sure.

Orgmode file:
```org
#+TITLE:Orgro citation tests

Cite a paper [cite:@jiang-2019-mechan-proper] here

* Footnotes
#+bibliography: Reference.bib
```

Reference.bib file:
```
@article{jiang-2019-mechan-proper,
  author =       {Bo Jiang and Wen Fang and Ruomeng Chen and Dongyu
                  Guo and Yinjie Huang and Chaolei Zhang and Yazheng
                  Liu},
  title =        {Mechanical Properties and Microstructural
                  Characterization of Medium Carbon Non-Quenched and
                  Tempered Steel - Microalloying Behavior},
  journal =      {Materials Science and Engineering: A},
  volume =       748,
  number =       {nil},
  pages =        {180-188},
  year =         2019,
  doi =          {10.1016/j.msea.2019.01.094},
  url =          {http://sci-hub.se/10.1016/j.msea.2019.01.094},
  DATE_ADDED =   {Fri Oct 28 17:16:26 2022},
}
```

**Comment by amake** [comment]
"No bibliographies found" means that Orgro wasn't able to detect the `#+bibliography:` line. I'm not able to reproduce this with your snippet.

With the snippet and bibliography as provided, instead I get a parser error when trying to parse the bibliography itself. I will fix that.

**Comment by llcc** [comment]
The `Footnotes` headline chunks with lots of metadata lines and footnotes. Not sure if it affects the parser. Also, my org file is pretty large. 

Below is an updated file:

```
#+TITLE:Orgro citation tests

Cite a paper [cite:@jiang-2019-mechan-proper] here [fn:1].
Another footnote [fn:2]

* Footnotes
[fn:1] https://github.com/amake/orgro/issues/104
[fn:2] https://github.com/amake/orgro/issues/101

#+bibliography: Reference.bib
#link: link https://github.com/amake/orgro/issues/%s
#+TODO: TODO(t) DOING(i) NEXT(n) PENDING(p) | CANCELLED(c) DONE(d)
#+STARTUP: overview logdrawer hidedrawers num
#+CUSTOM_FONT_KEYWORDS: t
#+auto_tangle: t
#+property: header-args:emacs-lisp :comments both :results silent :tangle no
# Local Variables:
# org-todo-keyword-faces: (("TODO" :foreground "red" :weight bold) ("DOING" :foreground "red" :weight bold) ("NEXT" :foreground "blue" :weight bold) ("DONE" :foreground "forest green" :weight bold) ("PENDING" :foreground "orange" :weight bold) ("CANCELLED" :foreground "forest green" :weight bold))
# org-num-max-level: 3
# line-spacing: 1
# End:

```

**Comment by amake** [comment]
OK thanks this time I can reproduce. The `#+bibliography:` line should be a reddish-orange if parsed correctly, but instead it is the color of plain text. I will fix this.

**Comment by amake** [comment]
OK I've figured this out.

Per [the manual](https://orgmode.org/manual/Creating-Footnotes.html) (emphasis mine):

> A footnote is started by a footnote marker in square brackets in column 0, no indentation allowed. **It ends at the next footnote definition, headline, or after two consecutive empty lines.**

The `[fn:2]` footnote encompasses everything below it, including the `#+bibliography:` line. You can see this if you export to HTML with `org-html-export-to-html` where that footnote becomes:

```html
<div class="footdef"><sup><a id="fn.2" class="footnum" href="#fnr.2" role="doc-backlink">2</a></sup> <div class="footpara" role="doc-footnote"><p class="footpara">
<a href="https://github.com/amake/orgro/issues/101">https://github.com/amake/orgro/issues/101</a>
</p>

<p class="footpara">
#link: link <a href="https://github.com/amake/orgro/issues/%s">https://github.com/amake/orgro/issues/%s</a>
</p></div></div>
```

(The lines starting with `#+` must be dropped at some point, but you can see that the `#link` line is not.)

This works in Org Mode because interpreting (recognizing the `#+bibliography:` line for the purposes of locating the .bib file) is done separately from parsing—it can both consider the `#+bibliography:` line to be part of the footnote *and* use it for resolving citations. Orgro, however, needs the result of parsing to produce a `#+bibliography:` OrgMeta node, whereas my parser considers footnotes to only contain rich text.

The short story is that if you add another empty line above the `#+bibliography:` line then your file will be "correct" and Orgro will handle it correctly.

On the other hand, Org Mode handles your file as desired (except on export), so I will see if it's worth trying to make my parser allow OrgMeta nodes within a footnote body.

**Comment by llcc** [comment]
> A footnote is started by a footnote marker in square brackets in column 0, no indentation allowed. **It ends at the next footnote definition, headline, or after two consecutive empty lines.**

I wasn’t aware of this before. Good to know!

> The short story is that if you add another empty line above the `#+bibliography:` line then your file will be "correct" and Orgro will handle it correctly.

Now orgro recognizes the bibliography file, but I got `Instance of 'ParserException': end of input expected (at 1:1)`, followed by `Citations not found`. Did you encounter the same issue you mentioned earlier?

**Comment by amake** [comment]
Look for 1.41.3 to be available for testing shortly. I fixed the BibTeX parser and allowed recognizing the `#+bibliography:` line inside footnotes.

**Comment by amake** [comment]
I should say however that the way I am presenting the citations does not look very nice with the very large entry in your .bib file. I'm not sure what the best approach would be.

**Comment by llcc** [comment]
Thanks for the quick fixation. I will feedback here when the new version is out!

**Comment by llcc** [comment]
> `Instance of 'ParserException': end of input expected (at 1:1)`, followed by `Citations not found`

The error still persists. 
I can send you my complete BibTeX file for testing. Would you please tell me your email?

**Comment by amake** [comment]
Sure, send it to support@orgro.org

**Comment by amake** [comment]
Thanks, I received your file. There were two things the parser didn't handle:

- Citation keys with characters other than `a-zA-Z0-9_:+-`. In particular your file has lots of keys containing hanzi.
- Un-delimited (not enclosed in `""` or `{}`) field values containing characters other than `a-zA-Z0-9`. In particular your file has a handful of entries with e.g. `url = http://example.com`.

I've updated the parser to handle these. Look for 1.41.4 coming soon.

**Comment by llcc** [comment]
@amake Thanks, it works like a charm. I'm really satisfied with the testing.

A small request: Some of the BibTeX entries include a DOI field. Would it be possible to make it a clickable URL in the popup, similar to the current functionality for URL field?

**Comment by amake** [comment]
Many of your entries have both a DOI and a URL field. I think it's hard to include both; should I prefer the URL when both are present?

**Comment by llcc** [comment]
DOI is preferable, if it not exists, use URL.

**Comment by llcc** [comment]
Thanks @amake.

**Comment by llcc** [comment]
@amake would you please promote the priority of url over DOI? If so, I can put the bibliography pdf OneDrive shared link into url field, so that I can open the pdf files on all platforms. If no url exists, then DOI can be used.

**Comment by amake** [comment]
> promote the priority of url over DOI

Coming in 1.41.2

**Comment by llcc** [comment]
Hi Araon, the feature bugs when the section is narrowed.  
The citation is unable to locate the bibliography file.

**Comment by amake** [comment]
It can only resolve bibliographies linked in the immediately visible region, so that is to be expected if the narrowed region does not have a `#+bibliography:` line.

**Comment by llcc** [comment]
Does it make sense that score the bibliography path for each org file in a global state during app's runtime, then all citations can access it even when narrowed?

**Comment by amake** [comment]
This will be addressed in v1.45.0:

- [iOS](https://testflight.apple.com/join/8YTxcuZC)
- [Android](https://play.google.com/store/apps/details?id=com.madlonkay.orgro)
